sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t masterzul/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true masterzul/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Docker-app-env"
  bucket_name: "elasticbeanstalk-us-east-1-975050046318"
  bucket_path: "docker-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: "$AWS_SECRET_KEY"
